version: "3.8"
services:
  postgres:
    image: "postgres:14.0"
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - "postgres:/var/lib/postgresql/data"

  currency-api:
    image: "docker.io/soundsofanarchy/currency-api:latest"
    depends_on:
      - postgres
      - migrations
    restart: "always"
    environment:
      CURRENCY_API_SERVER_ADDRESS: "0.0.0.0:8000"
      CURRENCY_API_DATABASE_HOST: "postgres"
      CURRENCY_API_DATABASE_PORT: "5432"
      CURRENCY_API_DATABASE_PASSWORD: "password"
      CURRENCY_API_LOGGER_LOG_LEVEL: "debug"
    ports:
      - "8000:8000"

volumes:
  postgres:
    driver: local