### /register
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/register
Content-Type: application/json

{
  "user": {
    "name": "artem",
    "middle_name": "mihaylov",
    "mail": "artem1@inbox.ru",
    "phone_number": "+1112312",
    "blocked": false,
    "registered": false,
    "admin": true,
    "password": "secretpass"
  }
}

### /register/approve
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/register/approve
Content-Type: application/json

{
  "user": {
    "id": 13
  }
}

### /login
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/login
Content-Type: application/json

{
  "phone_number": "+1112312",
  "password": "secretpass"
}

### /user/block   block == false - will unblock
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/user/block
Content-Type: application/json

{
  "user": {
    "id": 1
  },
  "block": false
}

### /user/list
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/user/list
Content-Type: application/json

{
  "offset": 0,
  "count": 100
}

### /user/info
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/user/info
Content-Type: application/json

{
  "id": 1
}

### /wallet/get
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/wallet/get
Content-Type: application/json

{
  "id": 123
}

### /wallet/create
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/wallet/create
Content-Type: application/json

{
  "wallet": {
    "id": 123,
    "user_id": 123,
    "currency": "USD",
    "value": 2000
  }
}

### /wallet/create
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/wallet/money/add
Content-Type: application/json

{
  "id": 123,
  "value": 2000
}

### /wallet/list
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/wallet/list
Content-Type: application/json

{
  "user_id": 1
}

### /wallet/exchange
POST http://ec2-35-88-92-18.us-west-2.compute.amazonaws.com:8000/wallet/exchange
Content-Type: application/json

{
  "user_id": 123,
  "from_wallet_id": 312,
  "to_wallet_id": 222,
  "from_currency": "RUB",
  "to_currency": "USD",
  "course": 0.016

}
